version: "3.4"

services:
  project35:
    build: drill-and-practice
    image: project35_img
    restart: "no"
    volumes:
      - ./drill-and-practice:/app
      - ./app-cache/:/app-cache
    ports:
      - 7777:7777
    depends_on:
      - database
      - flyway
    env_file:
      - project.env

  database:
    container_name: db_project_35
    image: postgres:14.1
    restart: "no"
    env_file:
      - project.env

  flyway:
    image: flyway/flyway:10.18.0-alpine
    depends_on:
      - database
    volumes:
      - ./flyway/sql:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate
    env_file:
      - project.env

  e2e-playwright:
    entrypoint: "/bin/true" # Prevent startup on docker-compose up
    build: playwright
    image: playwright
    network_mode: host
    depends_on:
      - project35
    volumes:
      - ./playwright/tests:/playwright/tests
